### PR TITLE
Re-add lost icons from extension separation

### PR DESCRIPTION
**Pull request by ymarco**
I've gone over all my deletions in #228 and fixed missing ones.
But that's what I also thought when making #228...

### CODE REVIEW

**Comment by wyuenho** [comment]
lol, thanks

**Comment by jacobilsoe** [comment]
Could this PR also have affected all-the-icons-dired to no longer do case insensitive matching?

**Comment by ymarco** [comment]
@jacobilsoe #228 might have, I didn't think about letter casing when writing it. 
The fix is simple though, I'll open a PR for it shortly

**Comment by ymarco** [comment]
@jacobilsoe see #268

**Comment by jacobilsoe** [comment]
@ymarco yep, works again now. Thanks!

**Pull request merged**
