### PR TITLE
Fix #184: void-function error in all-the-icons-icon-for-dir.

### LINKED ISSUE #184: Error in all-the-icons-icon-for-dir
Eval `(all-the-icons-icon-for-dir "c:/" nil "")` in GNU Emacs 26/27/28 on Windows.

```
Debugger entered--Lisp error: (void-function nil)
  nil(nil :v-adjust 0.0)
  apply(nil (nil :v-adjust 0.0))
  (cond ((file-symlink-p path) (all-the-icons-octicon "file-symlink-directory" :height 1.0 :v-adjust 0.0)) ((all-the-icons-dir-is-submodule path) (all-the-icons-octicon "file-submodule" :height 1.0 :v-adjust 0.0)) ((file-exists-p (format "%s/.git" path)) (format "%s" (all-the-icons-octicon "repo" :height 1.1 :v-adjust 0.0))) (t (apply (car matcher) (list (car (cdr matcher)) :v-adjust 0.0))))
  (let* ((matcher (all-the-icons-match-to-alist (file-name-base (directory-file-name dir)) all-the-icons-dir-icon-alist)) (path (expand-file-name dir)) (chevron (if chevron (all-the-icons-octicon (format "chevron-%s" chevron) :height 0.8 :v-adjust -0.1) "")) (padding (or padding "\11")) (icon (cond ((file-symlink-p path) (all-the-icons-octicon "file-symlink-directory" :height 1.0 :v-adjust 0.0)) ((all-the-icons-dir-is-submodule path) (all-the-icons-octicon "file-submodule" :height 1.0 :v-adjust 0.0)) ((file-exists-p (format "%s/.git" path)) (format "%s" (all-the-icons-octicon "repo" :height 1.1 :v-adjust 0.0))) (t (apply (car matcher) (list (car ...) :v-adjust 0.0)))))) (format "%s%s%s%s%s" padding chevron padding icon padding))
  all-the-icons-icon-for-dir("c:\\" nil "")
  (progn (all-the-icons-icon-for-dir "c:\\" nil ""))
  eval((progn (all-the-icons-icon-for-dir "c:\\" nil "")) t)
  elisp--eval-last-sexp(nil)
  #f(compiled-function (eval-last-sexp-arg-internal) "Evaluate sexp before point; print value in the echo area.\nInteractively, with a non `-' prefix argument, print output into\ncurrent buffer.\n\nNormally, this function truncates long output according to the\nvalue of the variables `eval-expression-print-length' and\n`eval-expression-print-level'.  With a prefix argument of zero,\nhowever, there is no such truncation.\nInteger values are printed in several formats (decimal, octal,\nand hexadecimal).  When the prefix argument is -1 or the value\ndoesn't exceed `eval-expression-print-maximum-character', an\ninteger value is also printed as a character of that codepoint.\n\nIf `eval-expression-debug-on-error' is non-nil, which is the default,\nthis command arranges for all errors to enter the debugger." (interactive "P") #<bytecode 0xe37ddd>)(nil)
  apply(#f(compiled-function (eval-last-sexp-arg-internal) "Evaluate sexp before point; print value in the echo area.\nInteractively, with a non `-' prefix argument, print output into\ncurrent buffer.\n\nNormally, this function truncates long output according to the\nvalue of the variables `eval-expression-print-length' and\n`eval-expression-print-level'.  With a prefix argument of zero,\nhowever, there is no such truncation.\nInteger values are printed in several formats (decimal, octal,\nand hexadecimal).  When the prefix argument is -1 or the value\ndoesn't exceed `eval-expression-print-maximum-character', an\ninteger value is also printed as a character of that codepoint.\n\nIf `eval-expression-debug-on-error' is non-nil, which is the default,\nthis command arranges for all errors to enter the debugger." (interactive "P") #<bytecode 0xe37ddd>) nil)
  eval-last-sexp(nil)
  funcall-interactively(eval-last-sexp nil)
  call-interactively(eval-last-sexp nil nil)
  #f(compiled-function (cmd &optional record-flag keys special) "Execute CMD as an editor command.\nCMD must be a symbol that satisfies the `commandp' predicate.\nOptional second arg RECORD-FLAG non-nil\nmeans unconditionally put this command in the variable `command-history'.\nOtherwise, that is done only if an arg is read using the minibuffer.\nThe argument KEYS specifies the value to use instead of (this-command-keys)\nwhen reading the arguments; if it is nil, (this-command-keys) is used.\nThe argument SPECIAL, if non-nil, means that this command is executing\na special event, so ignore the prefix argument and don't clear it." #<bytecode 0xe32ecb>)(eval-last-sexp nil nil nil)
  ad-Advice-command-execute(#f(compiled-function (cmd &optional record-flag keys special) "Execute CMD as an editor command.\nCMD must be a symbol that satisfies the `commandp' predicate.\nOptional second arg RECORD-FLAG non-nil\nmeans unconditionally put this command in the variable `command-history'.\nOtherwise, that is done only if an arg is read using the minibuffer.\nThe argument KEYS specifies the value to use instead of (this-command-keys)\nwhen reading the arguments; if it is nil, (this-command-keys) is used.\nThe argument SPECIAL, if non-nil, means that this command is executing\na special event, so ignore the prefix argument and don't clear it." #<bytecode 0xe32ecb>) eval-last-sexp)
  apply(ad-Advice-command-execute #f(compiled-function (cmd &optional record-flag keys special) "Execute CMD as an editor command.\nCMD must be a symbol that satisfies the `commandp' predicate.\nOptional second arg RECORD-FLAG non-nil\nmeans unconditionally put this command in the variable `command-history'.\nOtherwise, that is done only if an arg is read using the minibuffer.\nThe argument KEYS specifies the value to use instead of (this-command-keys)\nwhen reading the arguments; if it is nil, (this-command-keys) is used.\nThe argument SPECIAL, if non-nil, means that this command is executing\na special event, so ignore the prefix argument and don't clear it." #<bytecode 0xe32ecb>) eval-last-sexp)
  command-execute(eval-last-sexp)
```

### PR DESCRIPTION
**Pull request by seagle0128**
Fix #184 and #195.

### CODE REVIEW

**Comment by wyuenho** [comment]
Why would `all-the-icons-icon-for-dir` ever return nil? The last entry in the icons alist is a catch-all.

**Comment by seagle0128** [comment]
In #192 , If icon is nil `all-the-icons-icon-for-dir` returns nil. In this PR, I add an entry to catch all and returns the `default-directory` icon. And for better safety,  also check  in `all-the-icons-icon-for-dir-with-chevron`. The purpose of this PR is ensure `(car icon)` is non-nil.

**Comment by wyuenho** [comment]
You've misunderstood me. It is not possible for `all-the-icons-icon-for-dir` to return nil because there's a catch-all [here](https://github.com/domtronn/all-the-icons.el/blob/master/all-the-icons.el#L451). Even in this PR, you are still assuming it will return nil, even when it is impossible. What exactly is the issue you are trying to solve?

**Comment by seagle0128** [comment]
@wyuenho > The purpose of this PR is ensure `(car icon)` is non-nil. The apply calling throws the error.

**Comment by seagle0128** [comment]
@wyuenho Well. I understand what you exactly mean now.  

As the description on #184 , on Windows `(all-the-icons-icon-for-dir "c:/")` throws an error, since `(all-the-icons-match-to-alist dirname all-the-icons-dir-icon-alist)` returns nil. So If we don't change like this, we should improve `all-the-icons-match-to-alist` to avoid throwing errors (make sure `(car icon)` is non-nil). I am fine with enhancing `all-the-icons-match-to-alist` and close this PR.

**Comment by wyuenho** [comment]
> on Windows (all-the-icons-icon-for-dir "c:/") throws an error

Sorry, this makes no sense, it's the same regular expression. Which version of emacs are you using? Are you able to produce it with just all-the-icons under emacs -q?

**Comment by seagle0128** [comment]
@wyuenho The original reporter is @e190. Then I tested with Vanilla Emacs 26/27/28 (`emacs -Q`) on Windows 10. 

image

**Comment by wyuenho** [comment]
What do you get on Windows for `(directory-file-name "h:/")` and `(file-name-base (directory-file-name "h:/"))`?

**Comment by seagle0128** [comment]
> What do you get on Windows for `(directory-file-name "h:/")` and `(file-name-base (directory-file-name "h:/"))`?

`"h:/"` and `""`.

**Comment by wyuenho** [comment]
What about `(file-name-base (convert-standard-filename (directory-file-name "h:/")))` ?

**Comment by wyuenho** [comment]
Does it work? @seagle0128

**Comment by seagle0128** [comment]
@wyuenho Sorry for the late reply! So crazy busy this week.

>`(file-name-base (convert-standard-filename (directory-file-name "h:/")))`

Returns `""`.

**Comment by tpadioleau** [comment]
I'm having same issue with root directory on Ubuntu.

Why not just modifying this
```elisp
("." all-the-icons-octicon "file-directory"  :height 1.0 :v-adjust -0.1)
```
into this
```elisp
(".?" all-the-icons-octicon "file-directory"  :height 1.0 :v-adjust -0.1)
```
It should catch empty string which is generated because of root directory either on Linux or Windows systems.

**Comment by seagle0128** [comment]
@tpadioleau It's a simple solution. I can close this if you raise the PR.

**Pull request closed without merging**
